BoxLayout:
    orientation: 'vertical'
    Label:
        tex: 'Current trip location:'
    Spinner:
        id: spinner
        values: app.countries()
        on_text: app.chosen_currency_code()
    TextInput:
        multiline: False
    Label:
        id: home
        text: app.home_country()
    TextInput:
        multiline: False
    Label:
        text: 'Today is: ' + app.current_date()
        font_size: 36
    Label:
    Button: